package view;

import java.awt.BorderLayout;
import java.awt.datatransfer.DataFlavor;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDragEvent;
import java.awt.dnd.DropTargetDropEvent;
import java.awt.dnd.DropTargetEvent;
import java.awt.dnd.DropTargetListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author anhqu
 */
public class GUI_2_TabbedPaneMenu extends javax.swing.JPanel {

    private GUI1_1_MainFrame mainFrame;
    private boolean isValidFileImport;

    /**
     * Creates new form panel_PopUpMenu
     *
     * @param mainFrame
     */
    public GUI_2_TabbedPaneMenu(GUI1_1_MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        dragToImportFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPaneMenu = new javax.swing.JTabbedPane();
        question_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        categories_panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        import_panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        selectedFileContainer = new javax.swing.JLabel();
        btn_importFile = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();
        export_panel = new javax.swing.JPanel();

        TabbedPaneMenu.setForeground(new java.awt.Color(0, 159, 229));
        TabbedPaneMenu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabbedPaneMenuStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Slab Medium", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(193, 41, 36));
        jLabel1.setText("Question Bank");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Select a Category:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Also show questions from subcatagories");

        jCheckBox2.setText("Also show old questions");

        jButton1.setBackground(new java.awt.Color(0, 159, 229));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CREATE A NEW QUESTION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewQuestion(evt);
            }
        });

        javax.swing.GroupLayout question_panelLayout = new javax.swing.GroupLayout(question_panel);
        question_panel.setLayout(question_panelLayout);
        question_panelLayout.setHorizontalGroup(
            question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox1)
                    .addGroup(question_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(725, Short.MAX_VALUE))
        );
        question_panelLayout.setVerticalGroup(
            question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(question_panelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(question_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        TabbedPaneMenu.addTab("Questions", question_panel);

        jLabel3.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(193, 41, 36));
        jLabel3.setText("Add category");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Parent Category");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Category Info");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("ID number");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextField1.setText("jTextField1");
        jTextField1.setMinimumSize(new java.awt.Dimension(64, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField2.setText("jTextField2");

        jButton2.setBackground(new java.awt.Color(193, 41, 36));
        jButton2.setFont(new java.awt.Font("Roboto Slab", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD CATEGORY");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("There are required fields in this form marked");

        javax.swing.GroupLayout categories_panelLayout = new javax.swing.GroupLayout(categories_panel);
        categories_panel.setLayout(categories_panelLayout);
        categories_panelLayout.setHorizontalGroup(
            categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categories_panelLayout.createSequentialGroup()
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categories_panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(categories_panelLayout.createSequentialGroup()
                                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(310, 310, 310)
                                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)))))
                    .addGroup(categories_panelLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel8)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        categories_panelLayout.setVerticalGroup(
            categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categories_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(categories_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categories_panelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox2, jTextField1, jTextField2});

        TabbedPaneMenu.addTab("Categories", categories_panel);

        jLabel9.setFont(new java.awt.Font("Roboto Slab Medium", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(193, 41, 36));
        jLabel9.setText("Import questions from file");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(193, 41, 36));
        jLabel10.setText("File format");

        jLabel11.setText("Aiken format");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(193, 41, 36));
        jLabel12.setText("General");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(193, 41, 36));
        jLabel13.setText("Import questions from file");

        jLabel14.setText("Import");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/red_exclamation.png"))); // NOI18N

        jLabel17.setText("Maximum size for new files: 100MB");

        selectedFileContainer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedFileContainer.setText("You can drag and drop files here to add them");
        selectedFileContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        selectedFileContainer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        selectedFileContainer.setPreferredSize(new java.awt.Dimension(80, 16));

        btn_importFile.setBackground(new java.awt.Color(193, 41, 36));
        btn_importFile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_importFile.setForeground(new java.awt.Color(255, 255, 255));
        btn_importFile.setText("IMPORT");
        btn_importFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importFileActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("There are required fields in this form marked");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/red_exclamation.png"))); // NOI18N
        jLabel21.setText(".");

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/drop_arrow_open.png"))); // NOI18N
        jToggleButton1.setBorder(null);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/drop_arrow_open.png"))); // NOI18N
        jToggleButton2.setBorder(null);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/drop_arrow_close.png"))); // NOI18N
        jToggleButton3.setBorder(null);

        jButton4.setBackground(new java.awt.Color(0, 159, 229));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CHOOSE A FILE");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFile(evt);
            }
        });

        javax.swing.GroupLayout import_panelLayout = new javax.swing.GroupLayout(import_panel);
        import_panel.setLayout(import_panelLayout);
        import_panelLayout.setHorizontalGroup(
            import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(import_panelLayout.createSequentialGroup()
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(import_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jToggleButton3)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel12))
                    .addGroup(import_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jToggleButton2)
                        .addGap(1, 1, 1)
                        .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(import_panelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(310, 310, 310)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selectedFileContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(import_panelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btn_importFile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(import_panelLayout.createSequentialGroup()
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))))
                            .addComponent(jLabel13)))
                    .addGroup(import_panelLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel21))
                    .addGroup(import_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9))
                    .addGroup(import_panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jToggleButton1)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel10)
                        .addGap(310, 310, 310)
                        .addComponent(jLabel11)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        import_panelLayout.setVerticalGroup(
            import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(import_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11))
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jToggleButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(import_panelLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addComponent(jToggleButton2))
                .addGap(18, 18, 18)
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedFileContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_importFile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(import_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        TabbedPaneMenu.addTab("Import", import_panel);

        javax.swing.GroupLayout export_panelLayout = new javax.swing.GroupLayout(export_panel);
        export_panel.setLayout(export_panelLayout);
        export_panelLayout.setHorizontalGroup(
            export_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1031, Short.MAX_VALUE)
        );
        export_panelLayout.setVerticalGroup(
            export_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        TabbedPaneMenu.addTab("Export", export_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneMenu)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btn_importFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_importFileActionPerformed

    private void createNewQuestion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewQuestion
        // TODO add your handling code here:
        GUI3_2_Add_Question gui3_2_Add_Question = new GUI3_2_Add_Question(mainFrame);       
        mainFrame.getPanel_content().removeAll();
        gui3_2_Add_Question.setSize(1083, 530);
        gui3_2_Add_Question.setLocation(-20, 0);
        mainFrame.getPanel_content().add(gui3_2_Add_Question, BorderLayout.CENTER);
        mainFrame.validate();
        mainFrame.repaint();
    }//GEN-LAST:event_createNewQuestion

    private void chooseFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFile
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        //FileNameExtensionFilter txtFilter = new FileNameExtensionFilter("văn bản", "txt");
        //fileChooser.setFileFilter(txtFilter);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showDialog(this.import_panel, "CHOOSE A FILE");
        if (x == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            isValidFileImport = true;

            if (!file.getName().toLowerCase().endsWith(".txt")) {
                isValidFileImport = false;
                JOptionPane.showMessageDialog(GUI_2_TabbedPaneMenu.this, "Wrong Format", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (checkAikenFormat(file.getAbsolutePath()) != -1) {
                    isValidFileImport = false;
                    JOptionPane.showMessageDialog(GUI_2_TabbedPaneMenu.this, "Error at line " + checkAikenFormat(file.getAbsolutePath()), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            if (isValidFileImport == true) {
                Object[] options = {"OK"};
                JOptionPane.showOptionDialog(GUI_2_TabbedPaneMenu.this, "Import Complete!", "Notification",
                        JOptionPane.PLAIN_MESSAGE,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]);
            }
        }
    }//GEN-LAST:event_chooseFile

    private void TabbedPaneMenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabbedPaneMenuStateChanged
        // TODO add your handling code here:
        int selectedIndex = TabbedPaneMenu.getSelectedIndex();
        String selectedTabTitle = TabbedPaneMenu.getTitleAt(selectedIndex);
        mainFrame.getMainPath().setText("Home / My Courses / THI CUỐI KỲ" + " / " + selectedTabTitle);
    }//GEN-LAST:event_TabbedPaneMenuStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPaneMenu;
    private javax.swing.JButton btn_importFile;
    private javax.swing.JPanel categories_panel;
    private javax.swing.JPanel export_panel;
    private javax.swing.JPanel import_panel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel question_panel;
    private javax.swing.JLabel selectedFileContainer;
    // End of variables declaration//GEN-END:variables

    public JTabbedPane getTabbedPaneMenu() {
        return TabbedPaneMenu;
    }

    public void setTabbedPaneMenu(JTabbedPane TabbedPaneMenu) {
        this.TabbedPaneMenu = TabbedPaneMenu;
    }

    private void dragToImportFile() {
        DropTargetListener dropTargetListener = new DropTargetListener() {
            @Override
            public void dragEnter(DropTargetDragEvent dtde) {
            }

            @Override
            public void dragOver(DropTargetDragEvent dtde) {
            }

            @Override
            public void dropActionChanged(DropTargetDragEvent dtde) {
            }

            @Override
            public void dragExit(DropTargetEvent dte) {
            }

            @Override
            public void drop(DropTargetDropEvent event) {
                try {
                    event.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>) event.getTransferable().getTransferData(DataFlavor.javaFileListFlavor);
                    if (droppedFiles.size() > 1) {
                        JOptionPane.showMessageDialog(GUI_2_TabbedPaneMenu.this, "Only choose 1 file !", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        File file = droppedFiles.get(0);
                        isValidFileImport = true;
                        //System.out.println(file.getAbsolutePath());

                        if (!file.getName().toLowerCase().endsWith(".txt")) {
                            isValidFileImport = false;
                            JOptionPane.showMessageDialog(GUI_2_TabbedPaneMenu.this, "Wrong Format", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            if (checkAikenFormat(file.getAbsolutePath()) != -1) {
                                isValidFileImport = false;
                                JOptionPane.showMessageDialog(GUI_2_TabbedPaneMenu.this, "Error at line " + checkAikenFormat(file.getAbsolutePath()), "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                        if (isValidFileImport == true) {
                            Object[] options = {"OK"};
                            JOptionPane.showOptionDialog(GUI_2_TabbedPaneMenu.this, "Import Complete!", "Notification",
                                    JOptionPane.PLAIN_MESSAGE,
                                    JOptionPane.QUESTION_MESSAGE,
                                    null,
                                    options,
                                    options[0]);
                        }

//                        if (file.getName().toLowerCase().endsWith(".txt")) {
//                            Object[] options = {"OK"};
//                            JOptionPane.showOptionDialog(GUI_2_TabbedPaneMenu.this, "Import Complete!", "Notification",
//                                    JOptionPane.PLAIN_MESSAGE,
//                                    JOptionPane.QUESTION_MESSAGE,
//                                    null,
//                                    options,
//                                    options[0]);
//                        }
//                        else {
//                            JOptionPane.showMessageDialog(GUI_2_TabbedPaneMenu.this, "Wrong Format", "Error", JOptionPane.ERROR_MESSAGE);
//                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        DropTarget dropTarget = new DropTarget(selectedFileContainer, dropTargetListener);
        GUI_2_TabbedPaneMenu.this.selectedFileContainer.setDropTarget(dropTarget);
    }

    // Hàm kiểm tra định dạng aiken và trả về dòng đầu tiên bị lỗi (nếu có)
    public int checkAikenFormat(String fileName) {
        int errorLine = -1;
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            int lineNumber = 0;
            boolean inQuestion = false;
            boolean hasAnswer = false;
            Pattern answerPattern = Pattern.compile("^ANSWER:\\s[A-Z]$");
            while ((line = br.readLine()) != null) {
                lineNumber++;
                if (line.isEmpty()) {
                    if (inQuestion && !hasAnswer) {
                        errorLine = lineNumber;
                        return errorLine;
                    }
                    inQuestion = false;
                    hasAnswer = false;
                } else if (!inQuestion) {
                    inQuestion = true;
                } else {
                    Matcher answerMatcher = answerPattern.matcher(line);
                    if (answerMatcher.matches()) {
                        hasAnswer = true;
                    } else if (!line.matches("^[A-Z]\\.\\s.+")) {
                        errorLine = lineNumber;
                        return errorLine;
                    }
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return errorLine;
    }

}
